import { Case, Alert, ProcessingQueueItem, AuditLogEntry, PolicyMonitor, ComplianceMetric, CaseDocument } from '@/types';

// Mock Cases
export const mockCases: Case[] = [
  {
    id: 'case-001',
    caseNumber: 'H1B-2024-00847',
    applicantName: 'John Smith',
    applicantNameRedacted: 'John S***',
    aNumber: 'A123456789',
    visaType: 'H-1B',
    status: 'pending-review',
    aiConfidence: 92,
    assignedAttorney: 'Sarah Mitchell',
    assignedAttorneyId: 'att-001',
    filedDate: '2024-12-10',
    lastUpdated: '2024-12-18T10:30:00Z',
    employer: 'TechCorp Inc.',
    jobTitle: 'Senior Software Engineer',
    country: 'India',
  },
  {
    id: 'case-002',
    caseNumber: 'O1A-2024-00523',
    applicantName: 'Maria Garcia',
    applicantNameRedacted: 'Maria G***',
    visaType: 'O-1A',
    status: 'processing',
    aiConfidence: 87,
    assignedAttorney: 'James Rodriguez',
    assignedAttorneyId: 'att-002',
    filedDate: '2024-12-08',
    lastUpdated: '2024-12-17T15:45:00Z',
    employer: 'Research Labs LLC',
    jobTitle: 'Principal Scientist',
    country: 'Mexico',
  },
  {
    id: 'case-003',
    caseNumber: 'EB2-2024-01567',
    applicantName: 'Wei Zhang',
    applicantNameRedacted: 'Wei Z***',
    visaType: 'EB-2 NIW',
    status: 'approved',
    aiConfidence: 95,
    assignedAttorney: 'Sarah Mitchell',
    assignedAttorneyId: 'att-001',
    filedDate: '2024-11-15',
    lastUpdated: '2024-12-15T09:00:00Z',
    employer: 'Self-Petitioner',
    jobTitle: 'AI Researcher',
    country: 'China',
  },
  {
    id: 'case-004',
    caseNumber: 'L1A-2024-00234',
    applicantName: 'Amit Patel',
    applicantNameRedacted: 'Amit P***',
    visaType: 'L-1A',
    status: 'rfe-issued',
    aiConfidence: 68,
    assignedAttorney: 'James Rodriguez',
    assignedAttorneyId: 'att-002',
    filedDate: '2024-12-01',
    lastUpdated: '2024-12-16T14:20:00Z',
    employer: 'Global Solutions Inc.',
    jobTitle: 'Regional Director',
    country: 'India',
  },
  {
    id: 'case-005',
    caseNumber: 'H1B-2024-00912',
    applicantName: 'Yuki Tanaka',
    applicantNameRedacted: 'Yuki T***',
    visaType: 'H-1B',
    status: 'denied',
    aiConfidence: 45,
    assignedAttorney: 'Sarah Mitchell',
    assignedAttorneyId: 'att-001',
    filedDate: '2024-11-20',
    lastUpdated: '2024-12-14T11:30:00Z',
    employer: 'FinTech Startup',
    jobTitle: 'Data Analyst',
    country: 'Japan',
  },
  {
    id: 'case-006',
    caseNumber: 'O1B-2024-00189',
    applicantName: 'Elena Popov',
    applicantNameRedacted: 'Elena P***',
    visaType: 'O-1B',
    status: 'submitted',
    aiConfidence: 78,
    assignedAttorney: 'James Rodriguez',
    assignedAttorneyId: 'att-002',
    filedDate: '2024-12-12',
    lastUpdated: '2024-12-18T08:15:00Z',
    employer: 'Hollywood Studios',
    jobTitle: 'Film Director',
    country: 'Russia',
  },
  {
    id: 'case-007',
    caseNumber: 'EB1A-2024-00456',
    applicantName: 'Carlos Silva',
    applicantNameRedacted: 'Carlos S***',
    visaType: 'EB-1A',
    status: 'pending-review',
    aiConfidence: 89,
    assignedAttorney: 'Sarah Mitchell',
    assignedAttorneyId: 'att-001',
    filedDate: '2024-12-05',
    lastUpdated: '2024-12-17T16:00:00Z',
    employer: 'Self-Petitioner',
    jobTitle: 'Olympic Athlete',
    country: 'Brazil',
  },
  {
    id: 'case-008',
    caseNumber: 'H1B-2024-00998',
    applicantName: 'Priya Sharma',
    applicantNameRedacted: 'Priya S***',
    visaType: 'H-1B',
    status: 'processing',
    aiConfidence: 91,
    assignedAttorney: 'James Rodriguez',
    assignedAttorneyId: 'att-002',
    filedDate: '2024-12-11',
    lastUpdated: '2024-12-18T09:45:00Z',
    employer: 'CloudTech Solutions',
    jobTitle: 'DevOps Engineer',
    country: 'India',
  },
];

// Mock Alerts
export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    type: 'warning',
    title: 'RFE Response Due Soon',
    message: 'Case L1A-2024-00234 has an RFE response due in 3 days.',
    timestamp: '2024-12-18T10:00:00Z',
    caseId: 'case-004',
    read: false,
  },
  {
    id: 'alert-002',
    type: 'error',
    title: 'Citation Verification Failed',
    message: 'AI-generated citation could not be verified for case O1A-2024-00523.',
    timestamp: '2024-12-18T09:30:00Z',
    caseId: 'case-002',
    read: false,
  },
  {
    id: 'alert-003',
    type: 'success',
    title: 'Case Approved',
    message: 'Case EB2-2024-01567 has been approved by USCIS.',
    timestamp: '2024-12-15T09:00:00Z',
    caseId: 'case-003',
    read: true,
  },
  {
    id: 'alert-004',
    type: 'info',
    title: 'New Case Assigned',
    message: 'You have been assigned to case O1B-2024-00189.',
    timestamp: '2024-12-12T14:00:00Z',
    caseId: 'case-006',
    read: true,
  },
];

// Mock Processing Queue
export const mockProcessingQueue: ProcessingQueueItem[] = [
  {
    caseId: 'case-001',
    caseNumber: 'H1B-2024-00847',
    visaType: 'H-1B',
    stage: 'policy-matching',
    progress: 65,
    elapsedTime: 145,
    estimatedTime: 220,
  },
  {
    caseId: 'case-008',
    caseNumber: 'H1B-2024-00998',
    visaType: 'H-1B',
    stage: 'evidence-review',
    progress: 35,
    elapsedTime: 78,
    estimatedTime: 200,
  },
  {
    caseId: 'case-002',
    caseNumber: 'O1A-2024-00523',
    visaType: 'O-1A',
    stage: 'risk-assessment',
    progress: 80,
    elapsedTime: 180,
    estimatedTime: 225,
  },
];

// Mock Weekly Data for Charts
export const mockWeeklyData = [
  { date: 'Mon', approved: 12, denied: 2, pending: 8, rfe: 3 },
  { date: 'Tue', approved: 15, denied: 1, pending: 10, rfe: 4 },
  { date: 'Wed', approved: 10, denied: 3, pending: 12, rfe: 2 },
  { date: 'Thu', approved: 18, denied: 2, pending: 6, rfe: 5 },
  { date: 'Fri', approved: 14, denied: 4, pending: 9, rfe: 3 },
  { date: 'Sat', approved: 5, denied: 0, pending: 3, rfe: 1 },
  { date: 'Sun', approved: 3, denied: 1, pending: 2, rfe: 0 },
];

// Mock Metrics
export const mockMetrics = {
  casesProcessedToday: 127,
  casesProcessedChange: 12,
  pendingReview: 34,
  pendingReviewChange: -8,
  manualReviewRequired: 7,
  manualReviewChange: 3,
  systemHealth: 99.9,
  systemHealthChange: 0.1,
  totalCasesThisQuarter: 1247,
};

// Mock Audit Logs
export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: 'log-001',
    timestamp: '2024-12-18T10:32:00Z',
    userId: 'user-001',
    userName: 'Sarah Mitchell',
    userRole: 'Attorney',
    action: 'view',
    resource: 'Case Details',
    resourceId: 'case-001',
    caseNumber: 'H1B-2024-00847',
    ipAddress: '192.168.1.105',
    details: 'Viewed case details and AI analysis',
    riskLevel: 'low',
  },
  {
    id: 'log-002',
    timestamp: '2024-12-18T10:28:00Z',
    userId: 'user-002',
    userName: 'James Rodriguez',
    userRole: 'Attorney',
    action: 'edit',
    resource: 'Case Notes',
    resourceId: 'case-004',
    caseNumber: 'L1A-2024-00234',
    ipAddress: '192.168.1.110',
    details: 'Updated case notes with RFE response strategy',
    riskLevel: 'low',
  },
  {
    id: 'log-003',
    timestamp: '2024-12-18T10:15:00Z',
    userId: 'user-001',
    userName: 'Sarah Mitchell',
    userRole: 'Attorney',
    action: 'export',
    resource: 'Case Report',
    resourceId: 'case-003',
    caseNumber: 'EB2-2024-01567',
    ipAddress: '192.168.1.105',
    details: 'Exported final approval letter',
    riskLevel: 'medium',
  },
  {
    id: 'log-004',
    timestamp: '2024-12-18T09:45:00Z',
    userId: 'user-003',
    userName: 'Admin User',
    userRole: 'Administrator',
    action: 'approve',
    resource: 'AI Analysis',
    resourceId: 'case-002',
    caseNumber: 'O1A-2024-00523',
    ipAddress: '192.168.1.100',
    details: 'Approved AI-generated recommendation',
    riskLevel: 'high',
  },
  {
    id: 'log-005',
    timestamp: '2024-12-18T09:30:00Z',
    userId: 'user-001',
    userName: 'Sarah Mitchell',
    userRole: 'Attorney',
    action: 'login',
    resource: 'System',
    ipAddress: '192.168.1.105',
    details: 'Successful login from authorized device',
    riskLevel: 'low',
  },
  {
    id: 'log-006',
    timestamp: '2024-12-18T09:00:00Z',
    userId: 'user-002',
    userName: 'James Rodriguez',
    userRole: 'Attorney',
    action: 'create',
    resource: 'Document Upload',
    resourceId: 'case-006',
    caseNumber: 'O1B-2024-00189',
    ipAddress: '192.168.1.110',
    details: 'Uploaded supporting evidence documents',
    riskLevel: 'low',
  },
];

// Mock Policy Monitors
export const mockPolicyMonitors: PolicyMonitor[] = [
  {
    id: 'policy-001',
    name: 'PII Data Encryption',
    description: 'All personally identifiable information must be encrypted at rest and in transit.',
    category: 'data-privacy',
    status: 'compliant',
    lastCheck: '2024-12-18T10:00:00Z',
    nextCheck: '2024-12-18T11:00:00Z',
    violations: 0,
    totalChecks: 1250,
  },
  {
    id: 'policy-002',
    name: 'Access Control Review',
    description: 'User access permissions must be reviewed quarterly.',
    category: 'access-control',
    status: 'compliant',
    lastCheck: '2024-12-15T00:00:00Z',
    nextCheck: '2025-03-15T00:00:00Z',
    violations: 0,
    totalChecks: 45,
  },
  {
    id: 'policy-003',
    name: 'AI Model Hallucination Rate',
    description: 'AI-generated citations must have <1% hallucination rate.',
    category: 'ai-governance',
    status: 'warning',
    lastCheck: '2024-12-18T10:30:00Z',
    nextCheck: '2024-12-18T10:45:00Z',
    violations: 3,
    totalChecks: 450,
  },
  {
    id: 'policy-004',
    name: 'Data Retention Policy',
    description: 'Case data must be retained for 7 years after closure.',
    category: 'retention',
    status: 'compliant',
    lastCheck: '2024-12-17T00:00:00Z',
    nextCheck: '2024-12-24T00:00:00Z',
    violations: 0,
    totalChecks: 890,
  },
  {
    id: 'policy-005',
    name: 'Processing Time SLA',
    description: 'AI analysis must complete within 5 minutes for standard cases.',
    category: 'processing',
    status: 'compliant',
    lastCheck: '2024-12-18T10:30:00Z',
    nextCheck: '2024-12-18T10:35:00Z',
    violations: 12,
    totalChecks: 1856,
  },
  {
    id: 'policy-006',
    name: 'Audit Log Integrity',
    description: 'All system actions must be logged with immutable audit trail.',
    category: 'access-control',
    status: 'compliant',
    lastCheck: '2024-12-18T10:30:00Z',
    nextCheck: '2024-12-18T10:35:00Z',
    violations: 0,
    totalChecks: 25000,
  },
];

// Mock Compliance Metrics
export const mockComplianceMetrics: ComplianceMetric[] = [
  {
    id: 'metric-001',
    label: 'PII Protection Score',
    value: 98.5,
    target: 95,
    unit: '%',
    trend: 'up',
    status: 'compliant',
  },
  {
    id: 'metric-002',
    label: 'Access Review Completion',
    value: 100,
    target: 100,
    unit: '%',
    trend: 'stable',
    status: 'compliant',
  },
  {
    id: 'metric-003',
    label: 'Citation Accuracy',
    value: 99.3,
    target: 99,
    unit: '%',
    trend: 'up',
    status: 'compliant',
  },
  {
    id: 'metric-004',
    label: 'Avg Processing Time',
    value: 3.2,
    target: 5,
    unit: 'min',
    trend: 'down',
    status: 'compliant',
  },
  {
    id: 'metric-005',
    label: 'System Availability',
    value: 99.9,
    target: 99.5,
    unit: '%',
    trend: 'stable',
    status: 'compliant',
  },
  {
    id: 'metric-006',
    label: 'Audit Log Coverage',
    value: 100,
    target: 100,
    unit: '%',
    trend: 'stable',
    status: 'compliant',
  },
];

// Mock Documents
export const mockDocuments: CaseDocument[] = [
  {
    id: 'doc-001',
    name: 'Form I-129 Petition.pdf',
    type: 'form',
    category: 'forms',
    status: 'verified',
    ocrStatus: 'complete',
    aiStatus: 'ingested',
    caseId: 'case-001',
    caseNumber: 'H1B-2024-00847',
    uploadDate: '2024-12-10T09:00:00Z',
    fileSize: 2456789,
    uploadedBy: 'Sarah Mitchell',
    isRedacted: false,
  },
  {
    id: 'doc-002',
    name: 'Labor Condition Application.pdf',
    type: 'form',
    category: 'forms',
    status: 'verified',
    ocrStatus: 'complete',
    aiStatus: 'ingested',
    caseId: 'case-001',
    caseNumber: 'H1B-2024-00847',
    uploadDate: '2024-12-10T09:15:00Z',
    fileSize: 1234567,
    uploadedBy: 'Sarah Mitchell',
    isRedacted: false,
  },
  {
    id: 'doc-003',
    name: 'Degree Certificate - Masters CS.pdf',
    type: 'pdf',
    category: 'evidence',
    status: 'verified',
    ocrStatus: 'complete',
    aiStatus: 'ingested',
    caseId: 'case-001',
    caseNumber: 'H1B-2024-00847',
    uploadDate: '2024-12-10T09:30:00Z',
    fileSize: 892345,
    uploadedBy: 'Sarah Mitchell',
    isRedacted: true,
  },
  {
    id: 'doc-004',
    name: 'Passport Copy.pdf',
    type: 'pdf',
    category: 'evidence',
    status: 'verified',
    ocrStatus: 'complete',
    aiStatus: 'not-analyzed',
    caseId: 'case-001',
    caseNumber: 'H1B-2024-00847',
    uploadDate: '2024-12-10T09:45:00Z',
    fileSize: 3456789,
    uploadedBy: 'Sarah Mitchell',
    isRedacted: true,
  },
  {
    id: 'doc-005',
    name: 'AI Analysis Report.pdf',
    type: 'pdf',
    category: 'ai-reports',
    status: 'verified',
    ocrStatus: 'complete',
    aiStatus: 'ingested',
    caseId: 'case-001',
    caseNumber: 'H1B-2024-00847',
    uploadDate: '2024-12-18T10:30:00Z',
    fileSize: 567890,
    uploadedBy: 'System',
    isRedacted: false,
  },
  {
    id: 'doc-006',
    name: 'USCIS Policy Manual Reference.pdf',
    type: 'pdf',
    category: 'reference',
    status: 'verified',
    ocrStatus: 'complete',
    aiStatus: 'ingested',
    uploadDate: '2024-01-01T00:00:00Z',
    fileSize: 12456789,
    uploadedBy: 'System',
    isRedacted: false,
  },
  {
    id: 'doc-007',
    name: 'Research Publications.pdf',
    type: 'pdf',
    category: 'evidence',
    status: 'pending',
    ocrStatus: 'processing',
    aiStatus: 'processing',
    caseId: 'case-002',
    caseNumber: 'O1A-2024-00523',
    uploadDate: '2024-12-17T14:00:00Z',
    fileSize: 8901234,
    uploadedBy: 'James Rodriguez',
    isRedacted: false,
  },
  {
    id: 'doc-008',
    name: 'Employment Letter.pdf',
    type: 'pdf',
    category: 'evidence',
    status: 'verified',
    ocrStatus: 'complete',
    aiStatus: 'ingested',
    caseId: 'case-004',
    caseNumber: 'L1A-2024-00234',
    uploadDate: '2024-12-01T10:00:00Z',
    fileSize: 456789,
    uploadedBy: 'James Rodriguez',
    isRedacted: false,
  },
];
